pipelines:
  Build_calibreserver:
    group: calibreserver
    label_template: "${repository[:8]}"
    materials:
      repository:
        git: git@github.com:sebastianhutter/docker-calibreserver.git
    environment_variables:
      RANCHER_URL: https://rancher.hutter.cloud:8080
      # you can get the service id from the api view in rancher
      SERVICE_NAME_1: calibre-privat
      SERVICE_NAME_2: calibre-david
    stages:
      - Build:
          jobs:
            build:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - build_latest
               - exec:
                   command: make
                   arguments:
                    - build_commit
               - exec:
                   command: make
                   arguments:
                    - push_latest
               - exec:
                   command: make
                   arguments:
                    - push_commit
      - Deploy:
          jobs:
            deploy:
              tasks:
               - exec:
                  command: make
                  arguments:
                   - deploy_commit